#to offload picom's rendering to the gpu, thus reducing the cpu's work
backend = "glx";
glx-no-stencil =  true;
glx-copy-from-front = false;
#to reduce screen tearing, i.e. when the gpu sends more frames in a amt of time more than the refresh rate of the monitor
vsync = true;

#this is the leagcy method of blurring 
blur-method = "dual_kawase";
blur-strength = 6;
blur-background = true;
blur-background-fixed = false;   # blur strength follows opacity (default, but set explicitly)

#when the terminal is not focused it get's light 
#but when it's foucused it gets dark
opacity-rule = [
  "55:class_g = 'kitty' && !focused",
  "90:class_g = 'kitty' && focused"
];

#For fading animations
fading = true;
fade-delta = 4;
fade-exclude = [];

#Rounded-corners
corner-radius = 8;
rounded-corners-exclude = [
	"class_g = 'i3bar'"
];
#don't use the rules = ({...}), it's for v11 or newer


